# Generated by Django 5.0 on 2024-01-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravatar',
            old_name='avatar',
            new_name='user',
        ),
    ]
