# Generated by Django 5.0 on 2024-01-08 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_avatar_useravatar_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.useravatar'),
            preserve_default=False,
        ),
    ]
