# Generated by Django 5.0 on 2024-03-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_useravatar_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
