# Generated by Django 5.0 on 2024-02-08 19:42

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('freeDelivery', models.BooleanField(blank=True, default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=product.models.product_image_path)),
                ('alt', models.CharField(blank=True, max_length=50)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
