# Generated by Django 5.0 on 2024-02-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_reviews_product_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
