# Generated by Django 5.0 on 2024-02-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_reviews_reviews_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='images',
            new_name='product',
        ),
    ]
