# Generated by Django 5.0 on 2024-02-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='product.tag'),
        ),
    ]
