# Generated by Django 5.0 on 2024-03-27 18:44

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_category_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to=product.models.category_directory_path),
            preserve_default=False,
        ),
    ]
