# Generated by Django 5.0 on 2024-05-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_rename_name_category_title_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',)},
        ),
    ]
