# Generated by Django 5.0 on 2024-06-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='author',
            new_name='reviewer',
        ),
    ]
