# Generated by Django 5.0 on 2024-06-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_rename_author_reviews_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='author',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
