# Generated by Django 5.0 on 2024-06-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_email_remove_order_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_type',
            new_name='deliveryType',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_type',
            new_name='paymentType',
        ),
    ]
