# Generated by Django 5.0 on 2024-08-20 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0023_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('salePrice', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
            ],
        ),
    ]
