# Generated by Django 5.0 on 2024-08-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_category_options'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='ProductSale',
        ),
    ]
