# Generated by Django 5.0 on 2024-08-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_productsale_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='c',
        ),
    ]
